# Generated by Django 2.2.2 on 2019-06-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='useraccess',
            options={'verbose_name': 'UserAccess', 'verbose_name_plural': 'UserAccess'},
        ),
        migrations.AlterModelTable(
            name='profile',
            table='Profile',
        ),
        migrations.AlterModelTable(
            name='useraccess',
            table='UserAccess',
        ),
    ]
