# Generated by Django 2.2.2 on 2019-06-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190612_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccess',
            name='access_level',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
