# Generated by Django 2.2.2 on 2019-06-13 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190613_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_access',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.UserAccess'),
        ),
        migrations.AlterField(
            model_name='useraccess',
            name='access_level',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
