# Generated by Django 2.2.2 on 2019-06-09 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_code', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'AgentMaster',
                'verbose_name_plural': 'AgentMasters',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_no', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=9)),
                ('status', models.PositiveSmallIntegerField()),
                ('agent_master_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.AgentMaster')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agencies',
            },
        ),
    ]
