# Generated by Django 3.0 on 2020-05-03 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_abbreviation', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'State',
                'verbose_name_plural': 'States',
                'db_table': 'State',
            },
        ),
        migrations.AlterModelOptions(
            name='agentemail',
            options={'verbose_name': 'AgentEmail', 'verbose_name_plural': 'AgentEmails'},
        ),
        migrations.CreateModel(
            name='AgentAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=9)),
                ('agent_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
            ],
            options={
                'verbose_name': 'AgentAddress',
                'verbose_name_plural': 'AgentAddresses',
                'db_table': 'AgentAddress',
            },
        ),
    ]
