# Generated by Django 2.2.2 on 2019-06-09 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='agent',
            table='Agent',
        ),
        migrations.AlterModelTable(
            name='agentmaster',
            table='AgentMaster',
        ),
    ]
