# Generated by Django 2.2.2 on 2019-06-10 01:47

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_auto_20190609_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'PhoneType',
                'verbose_name_plural': 'PhoneTypes',
                'db_table': 'PhoneType',
            },
        ),
        migrations.CreateModel(
            name='AgentPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('phone_extension', models.CharField(max_length=20)),
                ('agent_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
                ('phone_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.PhoneType')),
            ],
            options={
                'verbose_name': 'AgentPhone',
                'verbose_name_plural': 'AgentPhones',
                'db_table': 'AgentPhone',
            },
        ),
    ]
