# Generated by Django 2.2.2 on 2019-06-10 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentphone_phonetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentphone',
            name='agent_no',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
        migrations.AlterField(
            model_name='agentphone',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.CreateModel(
            name='AgentEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('agent_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent')),
            ],
            options={
                'verbose_name': 'AgentEmail',
                'verbose_name_plural': 'AgentMails',
                'db_table': 'AgentEmail',
            },
        ),
    ]
