# Generated by Django 3.0 on 2020-05-03 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_portal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Portal',
        ),
    ]
