# Generated by Django 2.2.2 on 2019-06-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0004_auto_20190610_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentphone',
            name='phone_extension',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
