# Generated by Django 2.2.2 on 2019-06-11 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0006_auto_20190611_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentphone',
            name='agent_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agent.Agent'),
        ),
    ]
