# Generated by Django 2.2.2 on 2019-06-16 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0008_auto_20190611_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='agent_master_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agent.AgentMaster'),
        ),
    ]
