# Generated by Django 2.2.2 on 2019-06-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0009_auto_20190616_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentphone',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
