# Generated by Django 2.2.2 on 2019-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0010_auto_20190621_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentemail',
            name='portal',
            field=models.BooleanField(default=True),
        ),
    ]
