# Generated by Django 2.2.2 on 2019-06-22 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0011_agentemail_portal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentemail',
            old_name='portal',
            new_name='get_portal_emails',
        ),
    ]
